public with sharing class DataList {
    public DataList() {

    }
    // public static List<survey__c> findQuestions(){
    //     List<survey__c> surveylist= [SELECT 
    //     Answer1__c,	Question1__c,
    //     Answer2__c,	Question2__c,
    //     Answer3__c,	Question3__c,
    //     Answer4__c,	Question4__c,
    //     Answer5__c,	Question5__c,
    //     Answer6__c,	Question6__c,
    //     Answer7__c,	Question7__c,
    //     Answer8__c,	Question8__c,
    //     Answer9__c,	Question9__c,
    //     Answer10__c,Question10__c
    //     FROM survey__c where name = '调查问卷1'];
    //     return surveylist;
    // }

    // @AuraEnabled(cacheable=true)
    // public static LinkedList<String> findQuestion(){
    //     String Q1 = new String(surveylist.Question1__c);
    //     String Q2 = new String(surveylist.Question2__c);
    //     String Q3 = new String(surveylist.Question3__c);
    //     LinkedList<String> question = new LinkedList<String>();
    //     question.add(Q1);
    //     question.add(Q2);
    //     question.add(Q3);

    // }

     
}
